apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxbici
  labels:
    app: nginxbici
    version: "1.0"
spec:
  selector:
    matchLabels:
      app: nginxbici
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxbici
        version: "1.0"
    spec:
      containers:
        - name: frontbici
          image: icr.io/eduzora/nginxbici:v1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080
